
experimental = []

[cargo]
global_args = []

[cargo.command_args]

[package]
name = "tree-sitter-bridge"

[targets.android]
enabled = true
output = "dist/android"
min_sdk = 24

[targets.android.kotlin]
package = "starmage27.shumide"
desktop_loader = "bundled"
api_style = "top_level"
error_style = "throwing"
factory_style = "constructors"

[targets.android.kotlin.desktop_pack]
enabled = false

[targets.android.kotlin.type_mappings]

[targets.android.header]

[targets.android.pack]

[targets.android.debug_symbols]
enabled = false
format = "zip"
bundle = "unstripped"
standalone_archive = true

[targets.java.jvm]
enabled = false
output = "dist/java"
strip_symbols = false

[targets.java.jvm.debug_symbols]
enabled = false
format = "zip"
bundle = "unstripped"
standalone_archive = true

[targets.java.android]
enabled = false
output = "dist/java/android"
min_sdk = 24
